// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/chat.proto

package chat

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type None struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *None) Reset()         { *m = None{} }
func (m *None) String() string { return proto.CompactTextString(m) }
func (*None) ProtoMessage()    {}
func (*None) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_3f2ec72249544206, []int{0}
}
func (m *None) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_None.Unmarshal(m, b)
}
func (m *None) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_None.Marshal(b, m, deterministic)
}
func (dst *None) XXX_Merge(src proto.Message) {
	xxx_messageInfo_None.Merge(dst, src)
}
func (m *None) XXX_Size() int {
	return xxx_messageInfo_None.Size(m)
}
func (m *None) XXX_DiscardUnknown() {
	xxx_messageInfo_None.DiscardUnknown(m)
}

var xxx_messageInfo_None proto.InternalMessageInfo

type RequestAuthorize struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestAuthorize) Reset()         { *m = RequestAuthorize{} }
func (m *RequestAuthorize) String() string { return proto.CompactTextString(m) }
func (*RequestAuthorize) ProtoMessage()    {}
func (*RequestAuthorize) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_3f2ec72249544206, []int{1}
}
func (m *RequestAuthorize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestAuthorize.Unmarshal(m, b)
}
func (m *RequestAuthorize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestAuthorize.Marshal(b, m, deterministic)
}
func (dst *RequestAuthorize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestAuthorize.Merge(dst, src)
}
func (m *RequestAuthorize) XXX_Size() int {
	return xxx_messageInfo_RequestAuthorize.Size(m)
}
func (m *RequestAuthorize) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestAuthorize.DiscardUnknown(m)
}

var xxx_messageInfo_RequestAuthorize proto.InternalMessageInfo

func (m *RequestAuthorize) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ResponseAuthorize struct {
	SessionId            []byte   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseAuthorize) Reset()         { *m = ResponseAuthorize{} }
func (m *ResponseAuthorize) String() string { return proto.CompactTextString(m) }
func (*ResponseAuthorize) ProtoMessage()    {}
func (*ResponseAuthorize) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_3f2ec72249544206, []int{2}
}
func (m *ResponseAuthorize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseAuthorize.Unmarshal(m, b)
}
func (m *ResponseAuthorize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseAuthorize.Marshal(b, m, deterministic)
}
func (dst *ResponseAuthorize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseAuthorize.Merge(dst, src)
}
func (m *ResponseAuthorize) XXX_Size() int {
	return xxx_messageInfo_ResponseAuthorize.Size(m)
}
func (m *ResponseAuthorize) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseAuthorize.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseAuthorize proto.InternalMessageInfo

func (m *ResponseAuthorize) GetSessionId() []byte {
	if m != nil {
		return m.SessionId
	}
	return nil
}

type RequestConnect struct {
	SessionId            []byte   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestConnect) Reset()         { *m = RequestConnect{} }
func (m *RequestConnect) String() string { return proto.CompactTextString(m) }
func (*RequestConnect) ProtoMessage()    {}
func (*RequestConnect) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_3f2ec72249544206, []int{3}
}
func (m *RequestConnect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestConnect.Unmarshal(m, b)
}
func (m *RequestConnect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestConnect.Marshal(b, m, deterministic)
}
func (dst *RequestConnect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestConnect.Merge(dst, src)
}
func (m *RequestConnect) XXX_Size() int {
	return xxx_messageInfo_RequestConnect.Size(m)
}
func (m *RequestConnect) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestConnect.DiscardUnknown(m)
}

var xxx_messageInfo_RequestConnect proto.InternalMessageInfo

func (m *RequestConnect) GetSessionId() []byte {
	if m != nil {
		return m.SessionId
	}
	return nil
}

type CommandSay struct {
	SessionId            []byte   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandSay) Reset()         { *m = CommandSay{} }
func (m *CommandSay) String() string { return proto.CompactTextString(m) }
func (*CommandSay) ProtoMessage()    {}
func (*CommandSay) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_3f2ec72249544206, []int{4}
}
func (m *CommandSay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandSay.Unmarshal(m, b)
}
func (m *CommandSay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandSay.Marshal(b, m, deterministic)
}
func (dst *CommandSay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandSay.Merge(dst, src)
}
func (m *CommandSay) XXX_Size() int {
	return xxx_messageInfo_CommandSay.Size(m)
}
func (m *CommandSay) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandSay.DiscardUnknown(m)
}

var xxx_messageInfo_CommandSay proto.InternalMessageInfo

func (m *CommandSay) GetSessionId() []byte {
	if m != nil {
		return m.SessionId
	}
	return nil
}

func (m *CommandSay) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CommandLeave struct {
	SessionId            []byte   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandLeave) Reset()         { *m = CommandLeave{} }
func (m *CommandLeave) String() string { return proto.CompactTextString(m) }
func (*CommandLeave) ProtoMessage()    {}
func (*CommandLeave) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_3f2ec72249544206, []int{5}
}
func (m *CommandLeave) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandLeave.Unmarshal(m, b)
}
func (m *CommandLeave) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandLeave.Marshal(b, m, deterministic)
}
func (dst *CommandLeave) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandLeave.Merge(dst, src)
}
func (m *CommandLeave) XXX_Size() int {
	return xxx_messageInfo_CommandLeave.Size(m)
}
func (m *CommandLeave) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandLeave.DiscardUnknown(m)
}

var xxx_messageInfo_CommandLeave proto.InternalMessageInfo

func (m *CommandLeave) GetSessionId() []byte {
	if m != nil {
		return m.SessionId
	}
	return nil
}

type Event struct {
	// Types that are valid to be assigned to Event:
	//	*Event_None
	//	*Event_Join
	//	*Event_Leave
	//	*Event_Log
	//	*Event_Exit
	Event                isEvent_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_3f2ec72249544206, []int{6}
}
func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (dst *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(dst, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

type isEvent_Event interface {
	isEvent_Event()
}

type Event_None struct {
	None *EventNone `protobuf:"bytes,1,opt,name=none,proto3,oneof"`
}

type Event_Join struct {
	Join *EventJoin `protobuf:"bytes,2,opt,name=join,proto3,oneof"`
}

type Event_Leave struct {
	Leave *EventLeave `protobuf:"bytes,3,opt,name=leave,proto3,oneof"`
}

type Event_Log struct {
	Log *EventLog `protobuf:"bytes,4,opt,name=log,proto3,oneof"`
}

type Event_Exit struct {
	Exit *EventExit `protobuf:"bytes,5,opt,name=exit,proto3,oneof"`
}

func (*Event_None) isEvent_Event() {}

func (*Event_Join) isEvent_Event() {}

func (*Event_Leave) isEvent_Event() {}

func (*Event_Log) isEvent_Event() {}

func (*Event_Exit) isEvent_Event() {}

func (m *Event) GetEvent() isEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *Event) GetNone() *EventNone {
	if x, ok := m.GetEvent().(*Event_None); ok {
		return x.None
	}
	return nil
}

func (m *Event) GetJoin() *EventJoin {
	if x, ok := m.GetEvent().(*Event_Join); ok {
		return x.Join
	}
	return nil
}

func (m *Event) GetLeave() *EventLeave {
	if x, ok := m.GetEvent().(*Event_Leave); ok {
		return x.Leave
	}
	return nil
}

func (m *Event) GetLog() *EventLog {
	if x, ok := m.GetEvent().(*Event_Log); ok {
		return x.Log
	}
	return nil
}

func (m *Event) GetExit() *EventExit {
	if x, ok := m.GetEvent().(*Event_Exit); ok {
		return x.Exit
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Event) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Event_OneofMarshaler, _Event_OneofUnmarshaler, _Event_OneofSizer, []interface{}{
		(*Event_None)(nil),
		(*Event_Join)(nil),
		(*Event_Leave)(nil),
		(*Event_Log)(nil),
		(*Event_Exit)(nil),
	}
}

func _Event_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Event)
	// event
	switch x := m.Event.(type) {
	case *Event_None:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.None); err != nil {
			return err
		}
	case *Event_Join:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Join); err != nil {
			return err
		}
	case *Event_Leave:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Leave); err != nil {
			return err
		}
	case *Event_Log:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Log); err != nil {
			return err
		}
	case *Event_Exit:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Exit); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Event.Event has unexpected type %T", x)
	}
	return nil
}

func _Event_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Event)
	switch tag {
	case 1: // event.none
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EventNone)
		err := b.DecodeMessage(msg)
		m.Event = &Event_None{msg}
		return true, err
	case 2: // event.join
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EventJoin)
		err := b.DecodeMessage(msg)
		m.Event = &Event_Join{msg}
		return true, err
	case 3: // event.leave
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EventLeave)
		err := b.DecodeMessage(msg)
		m.Event = &Event_Leave{msg}
		return true, err
	case 4: // event.log
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EventLog)
		err := b.DecodeMessage(msg)
		m.Event = &Event_Log{msg}
		return true, err
	case 5: // event.exit
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EventExit)
		err := b.DecodeMessage(msg)
		m.Event = &Event_Exit{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Event_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Event)
	// event
	switch x := m.Event.(type) {
	case *Event_None:
		s := proto.Size(x.None)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Event_Join:
		s := proto.Size(x.Join)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Event_Leave:
		s := proto.Size(x.Leave)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Event_Log:
		s := proto.Size(x.Log)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Event_Exit:
		s := proto.Size(x.Exit)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type EventNone struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventNone) Reset()         { *m = EventNone{} }
func (m *EventNone) String() string { return proto.CompactTextString(m) }
func (*EventNone) ProtoMessage()    {}
func (*EventNone) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_3f2ec72249544206, []int{7}
}
func (m *EventNone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventNone.Unmarshal(m, b)
}
func (m *EventNone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventNone.Marshal(b, m, deterministic)
}
func (dst *EventNone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventNone.Merge(dst, src)
}
func (m *EventNone) XXX_Size() int {
	return xxx_messageInfo_EventNone.Size(m)
}
func (m *EventNone) XXX_DiscardUnknown() {
	xxx_messageInfo_EventNone.DiscardUnknown(m)
}

var xxx_messageInfo_EventNone proto.InternalMessageInfo

type EventJoin struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventJoin) Reset()         { *m = EventJoin{} }
func (m *EventJoin) String() string { return proto.CompactTextString(m) }
func (*EventJoin) ProtoMessage()    {}
func (*EventJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_3f2ec72249544206, []int{8}
}
func (m *EventJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventJoin.Unmarshal(m, b)
}
func (m *EventJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventJoin.Marshal(b, m, deterministic)
}
func (dst *EventJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventJoin.Merge(dst, src)
}
func (m *EventJoin) XXX_Size() int {
	return xxx_messageInfo_EventJoin.Size(m)
}
func (m *EventJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_EventJoin.DiscardUnknown(m)
}

var xxx_messageInfo_EventJoin proto.InternalMessageInfo

func (m *EventJoin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type EventLeave struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventLeave) Reset()         { *m = EventLeave{} }
func (m *EventLeave) String() string { return proto.CompactTextString(m) }
func (*EventLeave) ProtoMessage()    {}
func (*EventLeave) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_3f2ec72249544206, []int{9}
}
func (m *EventLeave) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventLeave.Unmarshal(m, b)
}
func (m *EventLeave) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventLeave.Marshal(b, m, deterministic)
}
func (dst *EventLeave) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventLeave.Merge(dst, src)
}
func (m *EventLeave) XXX_Size() int {
	return xxx_messageInfo_EventLeave.Size(m)
}
func (m *EventLeave) XXX_DiscardUnknown() {
	xxx_messageInfo_EventLeave.DiscardUnknown(m)
}

var xxx_messageInfo_EventLeave proto.InternalMessageInfo

func (m *EventLeave) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type EventLog struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventLog) Reset()         { *m = EventLog{} }
func (m *EventLog) String() string { return proto.CompactTextString(m) }
func (*EventLog) ProtoMessage()    {}
func (*EventLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_3f2ec72249544206, []int{10}
}
func (m *EventLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventLog.Unmarshal(m, b)
}
func (m *EventLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventLog.Marshal(b, m, deterministic)
}
func (dst *EventLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventLog.Merge(dst, src)
}
func (m *EventLog) XXX_Size() int {
	return xxx_messageInfo_EventLog.Size(m)
}
func (m *EventLog) XXX_DiscardUnknown() {
	xxx_messageInfo_EventLog.DiscardUnknown(m)
}

var xxx_messageInfo_EventLog proto.InternalMessageInfo

func (m *EventLog) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EventLog) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type EventExit struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventExit) Reset()         { *m = EventExit{} }
func (m *EventExit) String() string { return proto.CompactTextString(m) }
func (*EventExit) ProtoMessage()    {}
func (*EventExit) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_3f2ec72249544206, []int{11}
}
func (m *EventExit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventExit.Unmarshal(m, b)
}
func (m *EventExit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventExit.Marshal(b, m, deterministic)
}
func (dst *EventExit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventExit.Merge(dst, src)
}
func (m *EventExit) XXX_Size() int {
	return xxx_messageInfo_EventExit.Size(m)
}
func (m *EventExit) XXX_DiscardUnknown() {
	xxx_messageInfo_EventExit.DiscardUnknown(m)
}

var xxx_messageInfo_EventExit proto.InternalMessageInfo

func init() {
	proto.RegisterType((*None)(nil), "None")
	proto.RegisterType((*RequestAuthorize)(nil), "RequestAuthorize")
	proto.RegisterType((*ResponseAuthorize)(nil), "ResponseAuthorize")
	proto.RegisterType((*RequestConnect)(nil), "RequestConnect")
	proto.RegisterType((*CommandSay)(nil), "CommandSay")
	proto.RegisterType((*CommandLeave)(nil), "CommandLeave")
	proto.RegisterType((*Event)(nil), "Event")
	proto.RegisterType((*EventNone)(nil), "EventNone")
	proto.RegisterType((*EventJoin)(nil), "EventJoin")
	proto.RegisterType((*EventLeave)(nil), "EventLeave")
	proto.RegisterType((*EventLog)(nil), "EventLog")
	proto.RegisterType((*EventExit)(nil), "EventExit")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChatClient is the client API for Chat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatClient interface {
	Authorize(ctx context.Context, in *RequestAuthorize, opts ...grpc.CallOption) (*ResponseAuthorize, error)
	Connect(ctx context.Context, in *RequestConnect, opts ...grpc.CallOption) (Chat_ConnectClient, error)
	Say(ctx context.Context, in *CommandSay, opts ...grpc.CallOption) (*None, error)
	Leave(ctx context.Context, in *CommandLeave, opts ...grpc.CallOption) (*None, error)
}

type chatClient struct {
	cc *grpc.ClientConn
}

func NewChatClient(cc *grpc.ClientConn) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) Authorize(ctx context.Context, in *RequestAuthorize, opts ...grpc.CallOption) (*ResponseAuthorize, error) {
	out := new(ResponseAuthorize)
	err := c.cc.Invoke(ctx, "/Chat/Authorize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) Connect(ctx context.Context, in *RequestConnect, opts ...grpc.CallOption) (Chat_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Chat_serviceDesc.Streams[0], "/Chat/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatConnectClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Chat_ConnectClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type chatConnectClient struct {
	grpc.ClientStream
}

func (x *chatConnectClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatClient) Say(ctx context.Context, in *CommandSay, opts ...grpc.CallOption) (*None, error) {
	out := new(None)
	err := c.cc.Invoke(ctx, "/Chat/Say", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) Leave(ctx context.Context, in *CommandLeave, opts ...grpc.CallOption) (*None, error) {
	out := new(None)
	err := c.cc.Invoke(ctx, "/Chat/Leave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServer is the server API for Chat service.
type ChatServer interface {
	Authorize(context.Context, *RequestAuthorize) (*ResponseAuthorize, error)
	Connect(*RequestConnect, Chat_ConnectServer) error
	Say(context.Context, *CommandSay) (*None, error)
	Leave(context.Context, *CommandLeave) (*None, error)
}

func RegisterChatServer(s *grpc.Server, srv ChatServer) {
	s.RegisterService(&_Chat_serviceDesc, srv)
}

func _Chat_Authorize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAuthorize)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).Authorize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Chat/Authorize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).Authorize(ctx, req.(*RequestAuthorize))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RequestConnect)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServer).Connect(m, &chatConnectServer{stream})
}

type Chat_ConnectServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type chatConnectServer struct {
	grpc.ServerStream
}

func (x *chatConnectServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

func _Chat_Say_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandSay)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).Say(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Chat/Say",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).Say(ctx, req.(*CommandSay))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_Leave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandLeave)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).Leave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Chat/Leave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).Leave(ctx, req.(*CommandLeave))
	}
	return interceptor(ctx, in, info, handler)
}

var _Chat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Chat",
	HandlerType: (*ChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authorize",
			Handler:    _Chat_Authorize_Handler,
		},
		{
			MethodName: "Say",
			Handler:    _Chat_Say_Handler,
		},
		{
			MethodName: "Leave",
			Handler:    _Chat_Leave_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _Chat_Connect_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/chat.proto",
}

func init() { proto.RegisterFile("proto/chat.proto", fileDescriptor_chat_3f2ec72249544206) }

var fileDescriptor_chat_3f2ec72249544206 = []byte{
	// 385 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xc1, 0x4e, 0xea, 0x40,
	0x14, 0x86, 0xe9, 0xa5, 0x85, 0xdb, 0x53, 0xee, 0xbd, 0x30, 0xab, 0x5e, 0x12, 0x22, 0xa9, 0xc6,
	0xb8, 0x71, 0x30, 0x75, 0xe3, 0x56, 0x09, 0x09, 0x1a, 0xe3, 0xa2, 0x3e, 0x80, 0xa9, 0x70, 0x02,
	0x35, 0x74, 0x06, 0x99, 0x81, 0xa0, 0x8f, 0xe2, 0xa3, 0xf8, 0x74, 0xe6, 0x4c, 0x5b, 0x8a, 0x4a,
	0x64, 0x37, 0x73, 0xfe, 0xaf, 0x73, 0xfe, 0x39, 0xfd, 0x07, 0x9a, 0xf3, 0x85, 0xd4, 0xb2, 0x37,
	0x9a, 0xc6, 0x9a, 0x9b, 0x65, 0x50, 0x03, 0xfb, 0x4e, 0x0a, 0x0c, 0x8e, 0xa1, 0x19, 0xe1, 0xf3,
	0x12, 0x95, 0xbe, 0x5c, 0xea, 0xa9, 0x5c, 0x24, 0xaf, 0xc8, 0x18, 0xd8, 0x22, 0x4e, 0xd1, 0xb7,
	0xba, 0xd6, 0x89, 0x1b, 0x99, 0x75, 0x10, 0x42, 0x2b, 0x42, 0x35, 0x97, 0x42, 0x61, 0x09, 0x76,
	0x00, 0x14, 0x2a, 0x95, 0x48, 0xf1, 0x90, 0x8c, 0x0d, 0xde, 0x88, 0xdc, 0xbc, 0x72, 0x3d, 0x0e,
	0x7a, 0xf0, 0x37, 0x3f, 0xbb, 0x2f, 0x85, 0xc0, 0x91, 0xde, 0xf7, 0xc1, 0x00, 0xa0, 0x2f, 0xd3,
	0x34, 0x16, 0xe3, 0xfb, 0xf8, 0x65, 0x0f, 0xcc, 0x7c, 0xa8, 0xa7, 0xa8, 0x54, 0x3c, 0x41, 0xff,
	0x97, 0x31, 0x5a, 0x6c, 0x83, 0x53, 0x68, 0xe4, 0xc7, 0xdc, 0x62, 0xbc, 0xda, 0x6b, 0xf3, 0xdd,
	0x02, 0x67, 0xb0, 0x42, 0xa1, 0x59, 0x17, 0x6c, 0x21, 0x45, 0x76, 0x71, 0x2f, 0x04, 0x6e, 0xaa,
	0x34, 0xa6, 0x61, 0x25, 0x32, 0x0a, 0x11, 0x4f, 0x32, 0x11, 0xa6, 0xe3, 0x86, 0xb8, 0x91, 0x89,
	0x20, 0x82, 0x14, 0x76, 0x08, 0xce, 0x8c, 0xba, 0xfa, 0x55, 0x83, 0x78, 0x19, 0x62, 0x8c, 0x0c,
	0x2b, 0x51, 0xa6, 0xb1, 0x0e, 0x54, 0x67, 0x72, 0xe2, 0xdb, 0x06, 0x71, 0x73, 0x44, 0x4e, 0x86,
	0x95, 0x88, 0xea, 0xd4, 0x05, 0xd7, 0x89, 0xf6, 0x9d, 0xed, 0x2e, 0x83, 0x75, 0xa2, 0xa9, 0x0b,
	0x29, 0x57, 0x75, 0x70, 0x90, 0x8a, 0x81, 0x07, 0xee, 0xc6, 0x65, 0x70, 0x90, 0x6f, 0xc8, 0xd0,
	0xce, 0xbf, 0xd8, 0x05, 0x28, 0xed, 0xec, 0x24, 0x2e, 0xe0, 0x77, 0xe1, 0x66, 0x97, 0xfe, 0xc3,
	0xd4, 0x0b, 0x27, 0xe4, 0x33, 0x7c, 0xb3, 0xc0, 0xee, 0x4f, 0x63, 0xcd, 0x42, 0x70, 0xcb, 0xbc,
	0xb4, 0xf8, 0xd7, 0xac, 0xb5, 0x19, 0xff, 0x1e, 0xab, 0x23, 0xa8, 0x17, 0x81, 0xf9, 0xc7, 0x3f,
	0x27, 0xa8, 0x5d, 0xcb, 0x86, 0x71, 0x66, 0xb1, 0xff, 0x50, 0xa5, 0x94, 0x78, 0xbc, 0x8c, 0x4c,
	0xdb, 0xe1, 0x34, 0x07, 0xd6, 0x01, 0x27, 0xbb, 0xe1, 0x1f, 0xbe, 0x1d, 0x84, 0x5c, 0x7e, 0xac,
	0x99, 0x27, 0x70, 0xfe, 0x11, 0x00, 0x00, 0xff, 0xff, 0xff, 0x49, 0xc9, 0xee, 0x16, 0x03, 0x00,
	0x00,
}
